#!/usr/bin/env bash
# Real two-block SP1 recursion gate with bounded local CPU worker concurrency.
# These defaults trade throughput for memory. Callers can override each knob.
set -euo pipefail
cd "$(dirname "$0")/.."

export CARGO_BUILD_JOBS="${CARGO_BUILD_JOBS:-2}"
export RAYON_NUM_THREADS="${RAYON_NUM_THREADS:-4}"
# Show shard clock progress during long CPU runs without dumping proof objects.
export RUST_LOG="${RUST_LOG:-info,sp1_prover::worker::controller::splicing=debug,sp1_prover::worker::controller::global=debug}"
export SHARD_SIZE="${SHARD_SIZE:-1048576}"
export ELEMENT_THRESHOLD="${ELEMENT_THRESHOLD:-33554432}"
export HEIGHT_THRESHOLD="${HEIGHT_THRESHOLD:-262144}"
export MINIMAL_TRACE_CHUNK_THRESHOLD="${MINIMAL_TRACE_CHUNK_THRESHOLD:-1048576}"
export TRACE_CHUNK_SLOTS="${TRACE_CHUNK_SLOTS:-2}"
export SP1_WORKER_NUM_SPLICING_WORKERS="${SP1_WORKER_NUM_SPLICING_WORKERS:-1}"
export SP1_WORKER_SPLICING_BUFFER_SIZE="${SP1_WORKER_SPLICING_BUFFER_SIZE:-1}"
export SP1_WORKER_NUM_CORE_WORKERS="${SP1_WORKER_NUM_CORE_WORKERS:-1}"
export SP1_WORKER_CORE_BUFFER_SIZE="${SP1_WORKER_CORE_BUFFER_SIZE:-1}"
export SP1_WORKER_NUM_SETUP_WORKERS="${SP1_WORKER_NUM_SETUP_WORKERS:-1}"
export SP1_WORKER_SETUP_BUFFER_SIZE="${SP1_WORKER_SETUP_BUFFER_SIZE:-1}"
export SP1_WORKER_NUM_PREPARE_REDUCE_WORKERS="${SP1_WORKER_NUM_PREPARE_REDUCE_WORKERS:-1}"
export SP1_WORKER_PREPARE_REDUCE_BUFFER_SIZE="${SP1_WORKER_PREPARE_REDUCE_BUFFER_SIZE:-1}"
export SP1_WORKER_NUM_RECURSION_EXECUTOR_WORKERS="${SP1_WORKER_NUM_RECURSION_EXECUTOR_WORKERS:-1}"
export SP1_WORKER_RECURSION_EXECUTOR_BUFFER_SIZE="${SP1_WORKER_RECURSION_EXECUTOR_BUFFER_SIZE:-1}"
export SP1_WORKER_NUM_RECURSION_PROVER_WORKERS="${SP1_WORKER_NUM_RECURSION_PROVER_WORKERS:-1}"
export SP1_WORKER_RECURSION_PROVER_BUFFER_SIZE="${SP1_WORKER_RECURSION_PROVER_BUFFER_SIZE:-1}"
export SP1_WORKER_NUM_DEFERRED_WORKERS="${SP1_WORKER_NUM_DEFERRED_WORKERS:-1}"
export SP1_WORKER_DEFERRED_BUFFER_SIZE="${SP1_WORKER_DEFERRED_BUFFER_SIZE:-1}"

exec cargo test --locked --workspace --test consensus_chunk \
  consensus_guest_real_compressed_recursion -- --ignored --nocapture
