//! Entry-point trampoline: ELF `e_entry` lands here and jumps to the
//! macro-generated `_neutrino_main`.
//!
//! The shim is pure assembly so it can set up the stack pointer before
//! any Rust code runs. The linker script must define `_stack_top` at
//! the top of the runtime's writable memory region; the SDK does not
//! ship a default linker script for M2 because the layout is decided
//! by the runtime crate (Phase D ships the canonical one for
//! `neutrino-default-runtime`).
//!
//! `_start` semantics:
//!
//! 1. Initialise `sp` to `_stack_top`.
//! 2. Call into `_neutrino_main` (generated by the
//!    [`entrypoint`](crate::entrypoint) macro).
//! 3. If `_neutrino_main` ever returns — which it should not, because
//!    the macro wraps the user function with a trailing
//!    `abort(0)` — fall through to an explicit `abort(0)` and an
//!    infinite loop as belt-and-braces.

#![allow(unsafe_code)]

// SAFETY: `global_asm!` emits a `.text.init` section containing the
// ELF entry shim. The instructions only touch caller-saved registers
// and call symbols that the linker resolves from this crate or the
// dependent runtime crate. No Rust invariants are violated because no
// Rust code is running yet when `_start` executes.
core::arch::global_asm!(
    r#"
        .section .text.init, "ax"
        .globl _start
        .type _start, @function
    _start:
        la sp, _stack_top
        call _neutrino_main
        # _neutrino_main should never return. Fall through to abort(0).
        li a7, 0
        li a0, 0
        ecall
    1:
        j 1b
        .size _start, .-_start
    "#
);
